// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udymjuqutrkekaitrwys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkeW1qdXF1dHJrZWthaXRyd3lzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzQwMDMsImV4cCI6MjA2ODUxMDAwM30.umt7TxffG5rN1JaOpyMBb15seaMgnkfcgGQzrY7hv8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});